services:
  evosql:
    build: .
    ports:
      - "5433:5433"
      - "9967:9967"
    volumes:
      - evosql-data:/data
    environment:
      EVOSQL_USER_NAME: admin
      EVOSQL_PASSWORD: admin

  cli:
    build: ./cli
    depends_on:
      - evosql
    stdin_open: true
    tty: true
    entrypoint: ["sleep", "infinity"]

volumes:
  evosql-data:
