apiVersion: v1
kind: Service
metadata:
  name: {{ include "evolutiondb.fullname" . }}
  labels:
    {{- include "evolutiondb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - name: pg
      port: {{ .Values.service.pgPort }}
      targetPort: pg
      protocol: TCP
    - name: evo
      port: {{ .Values.service.evoPort }}
      targetPort: evo
      protocol: TCP
  selector:
    {{- include "evolutiondb.selectorLabels" . | nindent 4 }}
