#ifndef EVOLUTIONDB_VERSION_H
#define EVOLUTIONDB_VERSION_H

#define EVODB_VERSION_MAJOR 0
#define EVODB_VERSION_MINOR 2
#define EVODB_VERSION_PATCH 0
#define EVODB_VERSION       "0.2.0"

#endif /* EVOLUTIONDB_VERSION_H */
