#ifndef EVOLUTIONDB_VERSION_H
#define EVOLUTIONDB_VERSION_H

#define EVODB_VERSION_MAJOR 2
#define EVODB_VERSION_MINOR 0
#define EVODB_VERSION_PATCH 6
#define EVODB_VERSION       "2.0.6"

#endif /* EVOLUTIONDB_VERSION_H */
