apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "evolutiondb.fullname" . }}
  labels:
    {{- include "evolutiondb.labels" . | nindent 4 }}
data:
  EVOSQL_USER_NAME: {{ .Values.auth.username | quote }}
  {{- if .Values.machineId }}
  EVOSQL_MACHINE_ID: {{ .Values.machineId | quote }}
  {{- end }}
