{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evolutiondb.fullname" . }}
  labels:
    {{- include "evolutiondb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.password }}
  password: {{ .Values.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.encryption.enabled (not .Values.encryption.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evolutiondb.encryptionSecretName" . }}
  labels:
    {{- include "evolutiondb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.encryption.key }}
  encryption-key: {{ .Values.encryption.key | b64enc | quote }}
  {{- end }}
{{- end }}
