"""run_all.py — cross-vendor put / get latency sweep.

For each driver that's available at runtime we:

  1. setup() the vendor (drop+create / reset state)
  2. time `iters` memory_put calls
  3. time `iters` memory_get calls on the same keys
  4. teardown()

The result is one row per driver in a single markdown table at
`docs/benchmarks/v2-vendors.md`. Drivers whose `is_available()`
returns False (missing pip package, no service, no API key) are
skipped with a one-line note in the report so the reader knows
*why* a column is empty.
"""
from __future__ import annotations

import argparse
import datetime
import os
import sys
import traceback
from typing import List, Tuple

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))   # bench/

from vendors._base    import summarize_ms, time_op            # noqa: E402
from vendors.evosql_driver    import EvoSQLDriver             # noqa: E402
from vendors.mongo_driver     import MongoDriver              # noqa: E402
from vendors.mem0_driver      import Mem0Driver, Mem0CompatDriver  # noqa: E402
from vendors.zep_driver       import ZepDriver                # noqa: E402
from vendors.pinecone_driver  import PineconeDriver           # noqa: E402
from vendors.weaviate_driver  import WeaviateDriver           # noqa: E402


def bench_driver(driver, iters: int):
    """Returns (put_summary, get_summary, error_or_none)."""
    try:
        driver.setup()
    except Exception as e:
        return None, None, f"setup failed: {e}"

    try:
        # Phase 1 — put N rows.
        keys  = [f"k_{i}" for i in range(iters)]
        value = '{"role":"pm","team":"infra","tags":["alpha","beta"]}'
        put_iter = iter(keys)

        def put_op():
            k = next(put_iter)
            driver.memory_put("bench_ns", k, value)

        put_ms = time_op(put_op, iters)

        # Phase 2 — read them all back.
        get_iter = iter(keys)

        def get_op():
            k = next(get_iter)
            driver.memory_get("bench_ns", k)

        get_ms = time_op(get_op, iters)

    except Exception as e:
        traceback.print_exc()
        return None, None, f"runtime failed: {e}"
    finally:
        try:
            driver.teardown()
        except Exception:
            pass

    return summarize_ms(put_ms), summarize_ms(get_ms), None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--iters", type=int, default=100,
                    help="iterations per op (default 100)")
    ap.add_argument("--out", default=os.path.join(
        os.path.dirname(HERE), os.pardir,
        "docs", "benchmarks", "v2-vendors.md"))
    args = ap.parse_args()
    args.out = os.path.abspath(args.out)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)

    drivers = [
        EvoSQLDriver(),
        MongoDriver(),
        Mem0CompatDriver(),
        Mem0Driver(),
        ZepDriver(),
        PineconeDriver(),
        WeaviateDriver(),
    ]

    rows: List[Tuple[str, dict, dict, str]] = []
    print(f"=== cross-vendor sweep ({args.iters} iters/op) ===\n")
    for d in drivers:
        if not d.is_available():
            print(f"  SKIP   {d.name}  (driver not available)")
            rows.append((d.name, None, None, "not available"))
            continue
        print(f"  RUN    {d.name}")
        put_s, get_s, err = bench_driver(d, args.iters)
        if err:
            print(f"  FAIL   {d.name}: {err}")
            rows.append((d.name, None, None, err))
        else:
            print(f"  OK     {d.name}  put p99 = {put_s['p99']:.3f} ms,"
                  f"  get p99 = {get_s['p99']:.3f} ms")
            rows.append((d.name, put_s, get_s, ""))

    md = render_markdown(rows, args.iters)
    print("\n" + md)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(md)
    print(f"wrote {args.out}")
    return 0


def render_markdown(rows: List[Tuple[str, dict, dict, str]],
                      iters: int) -> str:
    out: List[str] = []
    out.append("# Cross-vendor agent-memory benchmarks (v2)")
    out.append("")
    out.append(f"_run at {datetime.datetime.utcnow().isoformat()}Z, "
               f"iters/op = {iters}_")
    out.append("")
    out.append("Generated by `bench/vendors/run_all.py`. Each driver "
               "is invoked through a uniform `memory_put` / "
               "`memory_get` interface so latency is apples-to-apples. "
               "Drivers whose dependent service or pip package is "
               "missing on the host are skipped — install the vendor's "
               "client + point the driver's environment variables at a "
               "running instance to fill in the row.")
    out.append("")
    out.append("| backend | n | put p50 | put p95 | put p99 | "
               "get p50 | get p95 | get p99 | note |")
    out.append("|---------|---|---------|---------|---------|"
               "---------|---------|---------|------|")
    for name, put_s, get_s, note in rows:
        if put_s is None:
            out.append(f"| {name} | — | — | — | — | — | — | — | "
                       f"_{note}_ |")
            continue
        out.append(
            f"| {name} | {int(put_s['n'])} | "
            f"{put_s['p50']:.3f} | {put_s['p95']:.3f} | "
            f"{put_s['p99']:.3f} | "
            f"{get_s['p50']:.3f} | {get_s['p95']:.3f} | "
            f"{get_s['p99']:.3f} | |"
        )
    out.append("")
    out.append("_units: milliseconds; vendors not pre-installed are "
               "marked **not available**._")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    sys.exit(main())
